const express = require('express')
const cors =require('cors')
const register = require('./Routes/register.js')
const login = require('./Routes/login.js')
require('dotenv').config()
const app = express()
app.use(express.urlencoded({extended:true}))
app.use(express.json())
app.use(cors())
app.use(register)
app.use(login)
app.listen(process.env.PORT || 5000,console.log('Workin on:',process.env.PORT || '5000'))